AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AWSServiceAccount:
    Description: Enter AWS Service Account Number
    Type: String
Transform: "AWS::LanguageExtensions"
Mappings:
  CustomVariables:
    qualys:
      qsstag: 'QualysSnapshotScanner'
Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: qualys-snapshot-scanner-cross-account
      Description: An execution role to be assumed by step function in source account
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - 'sts:AssumeRole'
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWSServiceAccount}:root"
          Action:
          - 'sts:AssumeRole'
      Tags:
        - Key: App
          Value: !FindInMap [CustomVariables, qualys, qsstag]
      Policies:
        - PolicyName: qualys-snapshot-manage
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - "ec2:DescribeInstances"
                - "ec2:DescribeVolumes"
                - "ec2:DescribeSnapshots"
                - "ec2:DescribeTags"
                - "ec2:CreateTags"
                - "ec2:CreateSnapshot"
                - "ec2:CopySnapshot"
                Resource: '*'
              - Effect: Allow
                Action:
                - "ec2:ModifySnapshotAttribute"
                - "ec2:DeleteSnapshot"   
                Resource: "arn:aws:ec2:*::snapshot/*"
                Condition:
                  StringEquals:
                    'aws:ResourceTag/Name': !FindInMap [CustomVariables, qualys, qsstag]
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:DescribeKey
                  - kms:RetireGrant
                  - kms:CreateGrant
                  - kms:ListGrants
                  - kms:ListAliases
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                Resource: "*"
                Condition:
                  StringNotEqualsIfExists:
                    aws:ResourceTag/QualysDoNotTouch: 'true'