name: Qualys IAC Scan 
on: workflow_dispatch
  schedule:
    - cron: '0 0 * * *'
jobs:
    Qualys_iac_scan:
        runs-on: ubuntu-latest
        name: Qualys IaC Scan
        steps:
          - name: Checkout
            uses: actions/checkout@v2 
            with:
                fetch-depth: 0
    
          - name: Qualys IAC scan action step
            uses: Qualys/github_action_qiac@main
            id: qiac
            env:
                URL: ${{ secrets.URL }}
                UNAME: ${{ secrets.USERNAME }}
                PASS: ${{ secrets.PASSWORD }}
                 
          - name: Qualys IAC scan action step
            uses: Qualys/github_action_qiac@main
            id: qiac2
            env:
                URL: ${{ secrets.URLCA }}
                UNAME: ${{ secrets.USERNAMECA }}
                PASS: ${{ secrets.PASSWORDCA }}
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v3
            if: always() 
            with:
                 sarif_file: response.sarif
